routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('index', 'HomeController@index');
    Route::get('user', 'UserController@index')->name('user.store');

    Route::resource('bidang', 'BidangController');
    Route::resource('sub-bidang', 'SubBidangController');
    Route::resource('jabatan', 'JabatanController');
    Route::resource('status-pegawai', 'StatusPegawaiController');
    Route::resource('pangkat-golongan', 'PangkatGolonganController');
    Route::resource('pangkat-eselon', 'PangkatEselonController');
    Route::resource('pekerja', 'PekerjaController');
    Route::resource('pendidikan', 'PendidikanController');
    Route::resource('diklat', 'DiklatController');
    Route::resource('riwayat-kerja', 'RiwayatKerjaController');
    Route::resource('keluarga', 'KeluargaController');
    Route::resource('kredit', 'KreditController');
    Route::resource('organisasi', 'OrganisasiController');
    Route::resource('penghargaan', 'PenghargaanController');
    Route::resource('promosi', 'PromosiController');
    Route::resource('cuti', 'CutiController');
    Route::resource('surat-cuti', 'SuratCutiController');
    Route::resource('pengguna', 'PenggunaController');
    Route::resource('group', 'GroupController');
    
});

//Auth::routes();
    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
//    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

resources/views/dashboard.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
    <div class="col-md-3 col-sm-6">
        <div class="iconic-w-wrap number-rotate">
            <span class="stat-w-title">Pegawai</span>
            <a href="{{ route('pekerja.index') }}" class="ico-cirlce-widget w_bg_cyan">
                <span><i class="fa fa-group"></i></span>
            </a>
            <div class="w-meta-info">
                <span class="w-meta-value number-animate" data-value="{{ $aktifPegawai + $nonAktifPegawai }}" data-animation-duration="1500">{{ $aktifPegawai + $nonAktifPegawai }}</span>
                <span class="w-meta-title">Orang</span>

            </div>
        </div>
    </div>

    <div class="col-md-3 col-sm-6">
        <div class="iconic-w-wrap iconic-w-wrap">
            <span class="stat-w-title">Pegawai Aktif</span>
            <a href="{{ route('pekerja.index') }}" class="ico-cirlce-widget w_bg_green">
                <span><i class="ico-user"></i></span>
            </a>
            <div class="w-meta-info">
                <span class="w-meta-value number-animate" data-value="{{ $aktifPegawai }}" data-animation-duration="1500">{{ $aktifPegawai }}</span>
                <span class="w-meta-title">Orang</span>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="iconic-w-wrap iconic-w-wrap">
            <span class="stat-w-title">Pegawai Tidak Aktif</span>
            <a href="{{ route('pekerja.index') }}" class="ico-cirlce-widget w_bg_blue_grey">
                <span><i class="fa fa-user-times"></i></span>
            </a>
            <div class="w-meta-info">
                <span class="w-meta-value number-animate" data-value="{{ $nonAktifPegawai }}" data-animation-duration="1500">{{ $nonAktifPegawai }}</span>
                <span class="w-meta-title">Orang</span>
            </div>
        </div>
    </div>

    <div class="col-md-3 col-sm-6">
        <div class="iconic-w-wrap iconic-w-wrap">
            <span class="stat-w-title">Pegawai Cuti</span>
            <a href="{{ route('pekerja.index') }}" class="ico-cirlce-widget w_bg_red">
                <span><i class="fa fa-street-view"></i></span>
            </a>
            <div class="w-meta-info">
                <span class="w-meta-value number-animate" data-value="{{ $cuti }}" data-animation-duration="1500">{{ $cuti }}</span>
                <span class="w-meta-title">Orang</span>
            </div>
        </div>
    </div>
</div>

<div class="row">
<div class="col-md-12">
        <div class="box-widget widget-module">
            <div class="widget-head clearfix">
                <span class="h-icon"><i class="fa fa-dashboard"></i></span>
                <h4>Selamat Datang</h4>
                <ul class="widget-action-bar pull-right">
                    <li><span class="waves-effect w-reload"><i class="fa fa-spinner"></i></span>
                    </li>
                </ul>
            </div>
            <div class="widget-container">
                <div class="table-responsive">
                    <table class="table w-order-list table-striped">
                        <thead>
                        <tr>
                            <th>
                                Selamat datang di {{ $title }} Manager.<br><br><br>
                            </th>
                            

                        </tr>
                        </thead>
                        
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection