routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('index', 'HomeController@index');
    Route::get('user', 'UserController@index')->name('user.store');

    Route::resource('bidang', 'BidangController');
    Route::resource('sub-bidang', 'SubBidangController');
    Route::resource('jabatan', 'JabatanController');
    Route::resource('status-pegawai', 'StatusPegawaiController');
    Route::resource('pangkat-golongan', 'PangkatGolonganController');
    Route::resource('pangkat-eselon', 'PangkatEselonController');
    Route::resource('pekerja', 'PekerjaController');
    Route::resource('pendidikan', 'PendidikanController');
    Route::resource('diklat', 'DiklatController');
    Route::resource('riwayat-kerja', 'RiwayatKerjaController');
    Route::resource('keluarga', 'KeluargaController');
    Route::resource('kredit', 'KreditController');
    Route::resource('organisasi', 'OrganisasiController');
    Route::resource('penghargaan', 'PenghargaanController');
    Route::resource('promosi', 'PromosiController');
    Route::resource('cuti', 'CutiController');
    Route::resource('surat-cuti', 'SuratCutiController');
    Route::resource('pengguna', 'PenggunaController');
    Route::resource('group', 'GroupController');
    
});

//Auth::routes();
    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
//    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Models/Kredit.php
<?php

namespace App\Models;

use App\Models\Pekerja;

use Illuminate\Database\Eloquent\Model;

class Kredit extends Model
{
    protected $guarded = [];

    public function Pekerja()
    {
        return $this->belongsTo(Pekerja::class);
    }
}

app/Http/Controllers/KreditController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Session;

use App\Models\Kredit;
use App\Models\Permission;
use Illuminate\Http\Request;

class KreditController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $modul_id = 26;
        $cek = Permission::where('modul_id', $modul_id)
                ->where('group_id', Auth::user()->group_id)->first();

        if ( $cek != "" ) {
            if ( $modul_id != $cek->modul_id) {
                return "<script language='javascript'>
                        alert('Anda Tidak Memiliki Akses');
                        document.location='".asset('/')."';
                        </script>";
            }
        } else {
            return "<script language='javascript'>
                    alert('Anda Tidak Memiliki Akses');
                    document.location='".asset('/')."';
                    </script>";
        }
        
        $this->validate($request, [
            'angka_kredit_lama' => 'required',
            'angka_kredit_baru' => 'required',
            'jumlah' => 'required',
            'penetapan' => 'required'
        ]);

        $kredit = Kredit::firstOrCreate([
            'angka_kredit_lama' => $request->angka_kredit_lama,
            'angka_kredit_baru' => $request->angka_kredit_baru,
            'jumlah' => $request->jumlah,
            'penetapan' => $request->penetapan,
            'pekerja_id' => $request->pekerja_id
        ]);
        
        
        Session::flash("flash_notif", [
            "level"     => "dismissible alert-success",
            "massage"   => "Berhasil, menyimpan data keluarga" . $kredit->pekerja->nama_pegawai
        ]);

        return redirect('kredit/'. $request->pekerja_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Kredit  $kredit
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $modul_id = 27;
        $cek = Permission::where('modul_id', $modul_id)
                ->where('group_id', Auth::user()->group_id)->first();

        if ( $cek != "" ) {
            if ( $modul_id != $cek->modul_id) {
                return "<script language='javascript'>
                        alert('Anda Tidak Memiliki Akses');
                        document.location='".asset('/')."';
                        </script>";
            }
        } else {
            return "<script language='javascript'>
                    alert('Anda Tidak Memiliki Akses');
                    document.location='".asset('/')."';
                    </script>";
        }
        
        $title = 'Sistem Informasi Pegawai Dinas Perumahan dan Permukiman Samarinda';
        $route = 'kredit';
        $button = 'Tambah';

        $kredit = Kredit::where('pekerja_id' , $id)->orderby('id','desc')->paginate(50);
        return view('kredit.index', compact('title', 'title', 'route', 'button', 'kredit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Kredit  $kredit
     * @return \Illuminate\Http\Response
     */
    public function edit(Kredit $kredit)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Kredit  $kredit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Kredit $kredit)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Kredit  $kredit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kredit $kredit)
    {
        $modul_id = 28;
        $cek = Permission::where('modul_id', $modul_id)
                ->where('group_id', Auth::user()->group_id)->first();

        if ( $cek != "" ) {
            if ( $modul_id != $cek->modul_id) {
                return "<script language='javascript'>
                        alert('Anda Tidak Memiliki Akses');
                        document.location='".asset('/')."';
                        </script>";
            }
        } else {
            return "<script language='javascript'>
                    alert('Anda Tidak Memiliki Akses');
                    document.location='".asset('/')."';
                    </script>";
        }
        
        $data = $kredit;
        $data->delete();
        Session::flash(
            "flash_notif",[
                "level"   => "dismissible alert-info",
                "massage" => "Berhasil Mengapus Data Angka Kredit <strong>" . $data->pekerja->nama_pegawai ."</strong>"
        ]);
        
        return redirect('kredit/'. $data->pekerja_id);
    }
}

resources/views/kredit/form.blade.php
{{ Form::hidden('pekerja_id', Request::segment(2)) }}

<div class="form-group{{ $errors->has('penetapan') ? ' has-error' : '' }}">
    {{ Form::label('penetapan', null, ['class' =>'col-sm-2 control-label']) }}
    <div class=" col-md-6">
        {{ Form::text('penetapan', null,['class' =>'form-control', 'placeholder'=> 'Penetapan']) }} 
        @if ($errors->has('penetapan'))
        <span class="help-block">
            <strong>{{ $errors->first('penetapan') }}</strong>
        </span>
        @endif
    </div>
</div>


<div class="form-group{{ $errors->has('angka_kredit_lama') ? ' has-error' : '' }}">
    {{ Form::label('angka_kredit_lama', null, ['class' =>'col-sm-2 control-label']) }}
    <div class=" col-md-6">
        {{ Form::text('angka_kredit_lama', null,['class' =>'form-control', 'placeholder'=> 'Angka Kredit Lama']) }} 
        @if ($errors->has('angka_kredit_lama'))
        <span class="help-block">
            <strong>{{ $errors->first('angka_kredit_lama') }}</strong>
        </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('angka_kredit_baru') ? ' has-error' : '' }}">
    {{ Form::label('angka_kredit_baru', null, ['class' =>'col-sm-2 control-label']) }}
    <div class=" col-md-6">
        {{ Form::text('angka_kredit_baru', null,['class' =>'form-control', 'placeholder'=> 'Angka Kredit Baru']) }} 
        @if ($errors->has('angka_kredit_baru'))
        <span class="help-block">
            <strong>{{ $errors->first('angka_kredit_baru') }}</strong>
        </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('jumlah') ? ' has-error' : '' }}">
    {{ Form::label('jumlah', null, ['class' =>'col-sm-2 control-label']) }}
    <div class=" col-md-6">
        {{ Form::text('jumlah', null,['class' =>'form-control', 'placeholder'=> 'Jumlah']) }} 
        @if ($errors->has('jumlah'))
        <span class="help-block">
            <strong>{{ $errors->first('jumlah') }}</strong>
        </span>
        @endif
    </div>
</div>

                
<div class="form-group">
    <div class="col-sm-8 col-sm-offset-4">
        {!! Form::submit($button, ['class' => 'btn btn-primary']) !!}
    </div>
</div>

resources/views/kredit/index.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
	<div class="col-md-12">
		<div class="box-widget widget-module">
				<div class="widget-head clearfix">
                    <span class="h-icon"><i class="fa fa-bars"></i></span>
                    <h4>{!! link_to_route('pekerja.show', 'Kembail', Request::segment(2), ['class' => 'btn btn-default'] ) !!}</h4>
                </div>

			<div class="widget-container">
				<div class=" widget-block">
            
            @include('template.notification')

            {!! Form::open(
               ['route' => [$route.'.store'], 
                'role'  => 'form',
                'method'=> 'post',
                'class' => 'form-horizontal',
                'files' => 'true']) !!}

                @include(
                    $route.'.form'
                )


            {!! Form::close() !!}

				</div>
			</div>

			<div class="widget-container">
				<div class="widget-block">
					<table id="users-table" class="table table-hover">
					<thead>
					<tr>
						<th>
							No
						</th>
						<th>
							Penetapan
						</th>
						<th>
							Angka Kredit Lama
						</th>
						<th>
							Angkat Kredit Baru
						</th>
						<th>
							Jumlah
						</th>
						<th>
							Aksi
						</th>
					</tr>
					</thead>
					<tbody>
					@foreach ($kredit as $index => $data)
						<tr>
						<td>
							{{ $index + 1 + ( ( $kredit->CurrentPage() - 1 ) * $kredit->PerPage() ) }}
						</td>
						<td>
							{{ $data->penetepan }}
						</td>
						<td>
							{{ $data->angka_kredit_lama }}
						</td>
						<td>
							{{ $data->angka_kredit_baru }}
						</td>
						<td>
							{{ $data->jumlah }}
						</td>
						<td class="tc-center">
<div class="btn-toolbar" role="toolbar">

        <div class="btn-employees" role="employees">
            {!! Form::open(['route' => [$route.'.destroy', $data->id], 'method' => 'delete', 'class' => 'form-inline', 'id' => "delete-form"]) !!}
                {!! Form::submit('Hapus', ['class' => 'btn btn-danger btn-sm', 'onclick' => "return confirmation();"]) !!}

            {!! Form::close() !!}
        </div>

</div>
						</td>
					</tr>
		            @endforeach
        			</tbody>
		  			</table>
					
				</div>
			</div>
		</div>
	</div>

</div>


@endsection